name: ci-conan

on: [pull_request, workflow_dispatch, push]

jobs:
  ci-conan-gcc-13:
    name: ci-conan-${{ matrix.conan_version }}-g++-13-static-release
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        conan_version: [1.64.1, 2.4.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Conan packages
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-conan-packages
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('conanfile.py') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Conan
        run: python -m pip install conan==${{ matrix.conan_version }}

      - name: Detect Conan profile
        run: conan profile detect --force --name=gcc-13

      - name: Build Conan package
        run: conan create -r conancenter conanfile.py -pr:b gcc-13 -pr:h gcc-13 --build=missing --build="beauty/*"
