name: ci-macos

on: [pull_request, workflow_dispatch]

jobs:
  ci-macos-clang-15:
    name: ci-macos-clang-15-static-release
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Cache Conan packages
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-conan-packages
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('conanfile.py') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Conan
        run: python -m pip install -r .github/requirements.txt

      - name: Detect Conan profile
        run: conan profile detect --force --name=clang-15

      - name: Install Conan Dependencies
        run: |
          conan install -r conancenter conanfile.py -of ${{ github.workspace }} -pr:b clang-15 -pr:h clang-15 --build=missing

      - name: Build
        run: |
          cmake -S . -B ${{ github.workspace }}/build -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=OFF
          cmake --build ${{ github.workspace }}/build
