name: ci-windows

on: [pull_request, workflow_dispatch]

jobs:
  ci-windows-msvc-19:
    name: ci-windows-msvc-19-static-release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Configure Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Cache Conan packages
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-conan-packages
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('conanfile.py') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Conan
        run: python -m pip install -r .github/requirements.txt

      - name: Detect Conan profile
        run: conan profile detect --force --name=msvc-19

      - name: Install Conan Dependencies
        run: |
          conan install -r conancenter conanfile.py -of ${{ github.workspace }} -pr:b msvc-19 -pr:h msvc-19 -s compiler.cppstd=17 --build=missing

      - name: Build
        run: |
          cmake -S . -B ${{ github.workspace }}/build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/build/conan_toolchain.cmake -DBUILD_SHARED_LIBS:BOOL=OFF -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_COMPILER=cl.exe -DCMAKE_C_COMPILER=cl.exe
          cmake --build ${{ github.workspace }}/build --config Release

